# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 'Random OKR Generator'
email: contact@stanleyidesis.com
description: > # this means to ignore newlines until "baseurl:"
  Objectives and Key Results for any business. Provide your product, industry, and value proposition 
  to generate the perfect OKR.
baseurl: '/random-okr-generator' # the subpath of your site, e.g. /blog
url: 'http://www.stanleyidesis.com' # the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: stanleyidesis
github_username:  stanidesis
permalink: /:slug

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
